name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout private workflow
        uses: actions/checkout@v3
        with:
          repository: toga4/github-actions-workflows
          ref: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./.github-private-actions

      - name: Run my action
        uses: ./.github-private-actions/build-image
        with:
          IMAGE_REPOSITORY: ghcr.io/toga4/use-private-workflow/hello
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
